"""DFU-first compiler core.

This package contains the current chip-level frontend and explicit lowering
pipeline from SRAM-backed logical tensor programs to DFU binary components.
"""

from __future__ import annotations

from gpdpu_compiler.core.chip_env import ChipEnv
from gpdpu_compiler.core.dfu3500 import (
    DFU3500_CHIP_CONFIG,
    DFU3500_GEMM_REGIONS,
    DFU3500_LOGICAL_FABRIC,
    DFU3500_MEMORY_LAYOUT,
    DFU3500_PHYSICAL_TOPOLOGY,
    DFU3500_SIMICT_LEGACY_RUNTIME_PROFILE,
    DFU3500SRAMRegion,
    VendorRuntimeProfile,
    chip_config_to_plan,
    gemm_region,
)
from gpdpu_compiler.core.dfu3500.legacy_templates import (
    Dfu3500TemplateBoundProgram,
    TemplateBoundInstruction,
    TemplateBoundSegment,
    lower_tile_micro_ops_to_dfu3500_template_bound,
)
from gpdpu_compiler.core.placement_types import Partial, Placement, Replicate, Shard
from gpdpu_compiler.core.program import (
    ChipOp,
    ChipProgram,
    LogicalDTensor,
    LogicalFabric,
    SRAMTensor,
)
from gpdpu_compiler.core.program_app import (
    AppPlan,
    AppPlanValidation,
)
from gpdpu_compiler.core.program_asm import (
    ProgramAsm,
    ProgramAsmBlock,
    ProgramAsmDependency,
    ProgramAsmInstruction,
    lower_dfu_packing_to_program_asm,
)
from gpdpu_compiler.core.program_bin import (
    ExeBlockConfBinRow,
    InstBinRow,
    InstructionLayoutRow,
    InstanceConfBinRow,
    ProgramBinReverseMap,
    ProgramBinRows,
    ProgramBinValidationReport,
    SubtaskConfBinRow,
    TaskConfBinRow,
    VendorInstMode,
    VendorLoopVariantBinding,
    lower_vendor_abi_to_program_bin_rows,
)
from gpdpu_compiler.core.program_bin_diff import (
    DecodedBundle,
    compare_simulator_bundle_rows,
    compare_simulator_bundles,
    decode_simulator_bundle,
)
from gpdpu_compiler.core.program_micro_ops import (
    TileMicroOp,
    TileMicroOpProgram,
    lower_processor_tile_to_micro_ops,
)
from gpdpu_compiler.core.program_nodes import (
    ProgramEdge,
    ProgramNode,
    ProgramNodeProgram,
    lower_processor_tile_to_program_nodes,
)
from gpdpu_compiler.core.program_packing import (
    DFUPackingProgram,
    EdgePackingBinding,
    NodePackingBinding,
    PackingContainer,
    PackingInstance,
    PackingTask,
    RepeatedTileLoopBodyTemplate,
    lower_program_nodes_to_dfu_packing,
)
from gpdpu_compiler.core.logical_plan import (
    LogicalDependency,
    LogicalReduceEdge,
    LogicalRouteEdge,
    LogicalRouteStep,
    ProcessorLocalValue,
    LogicalApp,
    ProcessorLogicalAction,
    LogicalPlan,
    LogicalStream,
)
from gpdpu_compiler.core.program_runtime import (
    RuntimePackage,
    RuntimePackageAssignment,
    assign_app_plan_to_runtime_packages,
)
from gpdpu_compiler.core.program_serializer import (
    ProgramBinComponent,
    ProgramBinComponents,
    ProgramBinPackage,
    lower_program_bin_rows_to_components,
)
from gpdpu_compiler.core.program_task_partition import (
    TaskAxisMesh,
    TaskAxisPlacement,
    TaskPartial,
    TaskPartitionPlan,
    TaskPartitionValidation,
    TaskReplicate,
    TaskShard,
)
from gpdpu_compiler.core.program_tile import (
    ProcessorTileActionRef,
    ProcessorTileActionStream,
    ProcessorTileProgram,
    ProcessorTileStream,
    TileAppStorageAction,
    TileBlockDependency,
    TileCollectiveBundle,
    TileComputeAction,
    TileDependency,
    TileLoopBodyInstance,
    TileLoopRegion,
    TileMicroBlock,
    TilePhase,
    TileProgramItemRef,
    TileRouteAction,
    TileStoreAction,
    TileSubtaskPlan,
    TileVisibilityRef,
    VendorTaskProjection,
    lower_processor_logical_to_tile_program,
)
from gpdpu_compiler.core.program_vendor_abi import (
    ProgramVendorABI,
    VendorExeBlockRow,
    VendorGraphEdge,
    VendorInstructionRange,
    VendorInstanceRow,
    VendorSubtaskRow,
    VendorTaskRow,
    lower_program_asm_to_vendor_abi,
)

__all__ = [
    "AppPlan",
    "AppPlanValidation",
    "ChipEnv",
    "ChipOp",
    "ChipProgram",
    "DFU3500_CHIP_CONFIG",
    "DFU3500_GEMM_REGIONS",
    "DFU3500_LOGICAL_FABRIC",
    "DFU3500_MEMORY_LAYOUT",
    "DFU3500_PHYSICAL_TOPOLOGY",
    "DFU3500_SIMICT_LEGACY_RUNTIME_PROFILE",
    "DFU3500SRAMRegion",
    "DFUPackingProgram",
    "Dfu3500TemplateBoundProgram",
    "DecodedBundle",
    "EdgePackingBinding",
    "ExeBlockConfBinRow",
    "InstBinRow",
    "InstructionLayoutRow",
    "InstanceConfBinRow",
    "LogicalDTensor",
    "LogicalDependency",
    "LogicalReduceEdge",
    "LogicalFabric",
    "LogicalRouteEdge",
    "LogicalRouteStep",
    "NodePackingBinding",
    "PackingContainer",
    "PackingInstance",
    "PackingTask",
    "Partial",
    "Placement",
    "ProcessorLocalValue",
    "LogicalApp",
    "ProcessorLogicalAction",
    "LogicalPlan",
    "LogicalStream",
    "ProcessorTileActionRef",
    "ProcessorTileActionStream",
    "ProcessorTileProgram",
    "ProcessorTileStream",
    "ProgramAsm",
    "ProgramAsmBlock",
    "ProgramAsmDependency",
    "ProgramAsmInstruction",
    "ProgramBinComponent",
    "ProgramBinComponents",
    "ProgramBinPackage",
    "ProgramBinReverseMap",
    "ProgramBinRows",
    "ProgramBinValidationReport",
    "ProgramEdge",
    "ProgramNode",
    "ProgramNodeProgram",
    "ProgramVendorABI",
    "RepeatedTileLoopBodyTemplate",
    "Replicate",
    "RuntimePackage",
    "RuntimePackageAssignment",
    "SRAMTensor",
    "Shard",
    "SubtaskConfBinRow",
    "TaskConfBinRow",
    "TaskAxisMesh",
    "TaskAxisPlacement",
    "TaskPartial",
    "TaskPartitionPlan",
    "TaskPartitionValidation",
    "TaskReplicate",
    "TaskShard",
    "TemplateBoundInstruction",
    "TemplateBoundSegment",
    "TileAppStorageAction",
    "TileBlockDependency",
    "TileCollectiveBundle",
    "TileComputeAction",
    "TileDependency",
    "TileLoopBodyInstance",
    "TileLoopRegion",
    "TileMicroBlock",
    "TileMicroOp",
    "TileMicroOpProgram",
    "TilePhase",
    "TileProgramItemRef",
    "TileRouteAction",
    "TileStoreAction",
    "TileSubtaskPlan",
    "TileVisibilityRef",
    "VendorTaskProjection",
    "VendorExeBlockRow",
    "VendorGraphEdge",
    "VendorInstMode",
    "VendorInstanceRow",
    "VendorInstructionRange",
    "VendorLoopVariantBinding",
    "VendorRuntimeProfile",
    "VendorSubtaskRow",
    "VendorTaskRow",
    "chip_config_to_plan",
    "compare_simulator_bundle_rows",
    "compare_simulator_bundles",
    "decode_simulator_bundle",
    "assign_app_plan_to_runtime_packages",
    "gemm_region",
    "lower_dfu_packing_to_program_asm",
    "lower_program_asm_to_vendor_abi",
    "lower_program_bin_rows_to_components",
    "lower_program_nodes_to_dfu_packing",
    "lower_processor_logical_to_tile_program",
    "lower_processor_tile_to_micro_ops",
    "lower_processor_tile_to_program_nodes",
    "lower_tile_micro_ops_to_dfu3500_template_bound",
    "lower_vendor_abi_to_program_bin_rows",
]
