"""Experimental stream compiler line.

This package is intentionally not wired into the main DFU3500 lowering path yet.
It hosts the left-to-right stream suffix lowering model described in
``compiler/notes/archive/logical-app-op-lowering-boundaries.md``.
"""

from .blocks import (
    FiberBlock,
    FiberBlockDependency,
    FiberBlockProjection,
    ProjectionValidationReport,
    probe_tile_micro_block_compat,
    project_fiber_to_blocks,
    summarize_fiber_block_projections,
    summarize_legacy_like_sequence,
    validate_fiber_block_projection,
)
from .binding import (
    SymbolicRoleBinding,
    SymbolicRoleBindingProgram,
    bind_executable_roles_symbolically,
    summarize_role_binding_program,
)
from .binary_plan import (
    BinaryBlobRegionPlan,
    BinaryInstructionPlan,
    BinaryInstancePlan,
    BinaryLayoutPlan,
    BinarySubtaskPlan,
    BinaryTaskPlan,
    BinaryZeroInstructionBoundary,
    lower_template_ops_to_binary_layout,
    summarize_binary_layout_plan,
)
from .dfu3500_semantics import (
    Dfu3500RoleSemanticRecord,
    Dfu3500RoleSemanticReport,
    lower_template_records_to_dfu3500_semantics,
    summarize_dfu3500_semantic_report,
)
from .debug_emit import (
    DebugRowArtifact,
    emit_debug_row_artifact,
    summarize_debug_row_artifact,
)
from .component_writers import (
    DebugComponentWriterArtifact,
    emit_debug_instance_conf_info_component,
    summarize_debug_component_writer_artifact,
)
from .executable import (
    ExecutableFiberOp,
    FiberExecutableProgram,
    lower_fibers_to_executable_ops,
    summarize_executable_program,
)
from .fiber import Fiber, FiberDependency, FiberOp, FragmentRef
from .fiber_patterns import (
    FiberPatternPlan,
    FiberPatternStep,
    FiberRepeatedRegion,
    TransitionalPatternId,
    build_matmul_sequential_reduction_pattern,
)
from .folding import (
    StreamLoopFoldCandidate,
    StreamLoopFoldReport,
    analyze_stream_loop_folding,
    summarize_stream_loop_fold_report,
)
from .folded_components import (
    FoldedTaskComponentCandidate,
    FoldedVendorComponentExperiment,
    build_folded_vendor_component_experiment,
    summarize_folded_vendor_component_experiment,
)
from .log10max_fiber_chain import (
    Log10MaxFiberChainOp,
    Log10MaxFiberChainReport,
    build_log10max_fiber_chain_report,
    summarize_log10max_fiber_chain_report,
)
from .relu_binding import (
    ExplicitReluSubtaskBinding,
    ExplicitReluSubtaskBindingReport,
    ReluDtypeDecision,
    ReluEvidenceRequirement,
    ReluStoreOperandLifetime,
    ReluTemplateBindingSeed,
    ReluZeroConstantPolicy,
    bind_explicit_relu_subtasks,
    summarize_explicit_relu_subtask_binding_report,
)
from .route_role_binding import (
    RouteRoleBindingRecord,
    RouteRoleBindingReport,
    build_route_role_binding_report,
    summarize_route_role_binding_report,
)
from .field_offsets import (
    FieldOffsetPreflightPlan,
    KnownFieldLayout,
    StructFieldPreflightRecord,
    StructOffsetPreflightReport,
    build_field_offset_preflight_plan,
    summarize_field_offset_preflight_plan,
)
from .serializer_readiness import (
    SerializerFieldReadiness,
    SerializerReadinessPlan,
    StructSerializerReadiness,
    build_serializer_readiness_plan,
    summarize_serializer_readiness_plan,
)
from .schedule import (
    FiberExecutionSchedule,
    FiberScheduleStep,
    RawFiberExecutionSchedule,
    ValidatedFiberExecutionSchedule,
    build_fiber_execution_schedule,
    ensure_validated_fiber_execution_schedule,
    summarize_fiber_execution_schedule,
    verify_fiber_execution_schedule,
)
from .stream import StreamAction, StreamPlan, StreamValue
from .template_records import (
    SymbolicTemplateRecord,
    SymbolicTemplateRecordProgram,
    lower_symbolic_bindings_to_template_records,
    summarize_template_record_program,
)
from .vendor_groups import (
    VendorLikeLocalRemapGroup,
    VendorLikeLocalRemapPlan,
    VendorLikeRowGroup,
    VendorLikeRowGroupPlan,
    group_debug_rows_vendor_like,
    remap_vendor_like_groups_locally,
    summarize_vendor_like_local_remap_plan,
    summarize_vendor_like_row_group_plan,
)
from .vendor_components import (
    VendorComponentPlan,
    build_vendor_component_plan,
    summarize_vendor_component_plan,
)
from .vendor_assembler_bundle import (
    VendorAssemblerCsvRow,
    VendorAssemblerInputBundle,
    VendorAssemblerSubtaskPlan,
    VendorAssemblerTaskPlan,
    VendorAssemblerTemplateCsv,
    build_vendor_assembler_input_bundle,
    summarize_vendor_assembler_input_bundle,
    write_vendor_assembler_input_bundle,
)
from .template_ops import (
    Diagnostic,
    InstructionIntent,
    TemplateOp,
    TemplateOpPlan,
    TemplateOpProvenance,
    TemplateResourceRequirement,
    lower_schedule_to_template_ops,
    summarize_template_op_plan,
)

__all__ = [
    "ExecutableFiberOp",
    "Fiber",
    "FiberBlock",
    "FiberBlockDependency",
    "FiberBlockProjection",
    "FiberDependency",
    "FiberExecutableProgram",
    "FiberOp",
    "FiberPatternPlan",
    "FiberPatternStep",
    "FiberRepeatedRegion",
    "FiberExecutionSchedule",
    "ExplicitReluSubtaskBinding",
    "ExplicitReluSubtaskBindingReport",
    "ReluDtypeDecision",
    "ReluEvidenceRequirement",
    "ReluStoreOperandLifetime",
    "ReluTemplateBindingSeed",
    "ReluZeroConstantPolicy",
    "RouteRoleBindingRecord",
    "RouteRoleBindingReport",
    "RawFiberExecutionSchedule",
    "ValidatedFiberExecutionSchedule",
    "StreamLoopFoldCandidate",
    "StreamLoopFoldReport",
    "FiberScheduleStep",
    "FieldOffsetPreflightPlan",
    "FoldedTaskComponentCandidate",
    "FoldedVendorComponentExperiment",
    "FragmentRef",
    "KnownFieldLayout",
    "Log10MaxFiberChainOp",
    "Log10MaxFiberChainReport",
    "BinaryBlobRegionPlan",
    "BinaryInstructionPlan",
    "BinaryInstancePlan",
    "BinaryLayoutPlan",
    "BinarySubtaskPlan",
    "BinaryTaskPlan",
    "BinaryZeroInstructionBoundary",
    "DebugRowArtifact",
    "DebugComponentWriterArtifact",
    "Diagnostic",
    "InstructionIntent",
    "ProjectionValidationReport",
    "SerializerFieldReadiness",
    "SerializerReadinessPlan",
    "StreamAction",
    "StreamPlan",
    "StreamValue",
    "StructFieldPreflightRecord",
    "StructOffsetPreflightReport",
    "StructSerializerReadiness",
    "TemplateOp",
    "TemplateOpPlan",
    "TemplateOpProvenance",
    "TemplateResourceRequirement",
    "TransitionalPatternId",
    "VendorLikeLocalRemapGroup",
    "VendorLikeLocalRemapPlan",
    "VendorLikeRowGroup",
    "VendorLikeRowGroupPlan",
    "VendorComponentPlan",
    "VendorAssemblerCsvRow",
    "VendorAssemblerInputBundle",
    "VendorAssemblerSubtaskPlan",
    "VendorAssemblerTaskPlan",
    "VendorAssemblerTemplateCsv",
    "SymbolicRoleBinding",
    "SymbolicRoleBindingProgram",
    "SymbolicTemplateRecord",
    "SymbolicTemplateRecordProgram",
    "Dfu3500RoleSemanticRecord",
    "Dfu3500RoleSemanticReport",
    "bind_executable_roles_symbolically",
    "analyze_stream_loop_folding",
    "build_fiber_execution_schedule",
    "build_matmul_sequential_reduction_pattern",
    "bind_explicit_relu_subtasks",
    "ensure_validated_fiber_execution_schedule",
    "build_field_offset_preflight_plan",
    "build_folded_vendor_component_experiment",
    "build_log10max_fiber_chain_report",
    "build_route_role_binding_report",
    "build_serializer_readiness_plan",
    "build_vendor_component_plan",
    "build_vendor_assembler_input_bundle",
    "emit_debug_row_artifact",
    "emit_debug_instance_conf_info_component",
    "group_debug_rows_vendor_like",
    "lower_fibers_to_executable_ops",
    "lower_template_ops_to_binary_layout",
    "lower_symbolic_bindings_to_template_records",
    "lower_template_records_to_dfu3500_semantics",
    "lower_schedule_to_template_ops",
    "probe_tile_micro_block_compat",
    "project_fiber_to_blocks",
    "remap_vendor_like_groups_locally",
    "summarize_executable_program",
    "summarize_field_offset_preflight_plan",
    "summarize_folded_vendor_component_experiment",
    "summarize_log10max_fiber_chain_report",
    "summarize_binary_layout_plan",
    "summarize_debug_row_artifact",
    "summarize_debug_component_writer_artifact",
    "summarize_fiber_execution_schedule",
    "summarize_stream_loop_fold_report",
    "summarize_fiber_block_projections",
    "summarize_legacy_like_sequence",
    "summarize_role_binding_program",
    "summarize_explicit_relu_subtask_binding_report",
    "summarize_route_role_binding_report",
    "summarize_serializer_readiness_plan",
    "summarize_template_record_program",
    "summarize_template_op_plan",
    "summarize_dfu3500_semantic_report",
    "summarize_vendor_like_local_remap_plan",
    "summarize_vendor_like_row_group_plan",
    "summarize_vendor_component_plan",
    "summarize_vendor_assembler_input_bundle",
    "write_vendor_assembler_input_bundle",
    "validate_fiber_block_projection",
    "verify_fiber_execution_schedule",
]
