"""Built-in DFU binary decoder profiles."""

from .dfu3500 import DFU3500_SIMICT_LEGACY_PROFILE

BUILTIN_PROFILES = {
    DFU3500_SIMICT_LEGACY_PROFILE.profile_id: DFU3500_SIMICT_LEGACY_PROFILE,
}

__all__ = ["BUILTIN_PROFILES", "DFU3500_SIMICT_LEGACY_PROFILE"]
